### ISSUE TITLE
How to take picture sequentially?

### ISSUE THREAD

**Issue by bahacan19** [sandrios/sandriosCamera#10]
Hi
I want a user can take pictures as many as he/she wants on camera screen.
Without starting a previewActivity how can i achieve this?
Right now i found an unpleasant solution on `BaseSandriosActivity.java` . which is :
 ```java
@Override
    public void onPhotoTaken() {
//        startPreviewActivity();
        getCameraController().onPause();
        getCameraController().onResume();
        Toast.makeText(this, "uri   :" +  getCameraController().getOutputFile().toString(), Toast.LENGTH_SHORT).show();
    }
```
and causes screen freeze 1-2 second.

Thanks in advance

**Comment by arpitgandhi9** [comment]
Hello @bahacan19. Currently it is not possible to capture multiple images.

Also by multiple images, what do you mean burst mode or capturing images one by one?

**Comment by bahacan19** [comment]
@arpitgandhi9 capturing images one by one, i meant
