### ISSUE TITLE
Captured image orientation changes while upload to server

### ISSUE THREAD

**Issue by lendra85** [sandrios/sandriosCamera#11]
I had capture the photo using camera, it was good when displaying from preview screen, but after the image path has uplloaded then the orientation changed -90 degrees.
I tried to detect the orientation of file by ExifInterface, but always return 0.
How i can solve this?

**Comment by sohambannerjee8** [comment]
Even I am also facing the same.Please let me know if anyone found any solution.

**Comment by jeetdholakia** [comment]
Same issue here. Please fix.

**Comment by faisaldebouni** [comment]
you'll have to rotate image (either after or before upload). there is a header in the image meta data which will specify the orientation the image was taken in.

this function will rotate image to correct orientation (php/server side)
https://stackoverflow.com/a/21797668

this for rotating before upload (java)
https://stackoverflow.com/a/14066265

**Comment by arpitgandhi9** [comment]
Please checkout 90b79ac3f and let me know if this fixes the issue.
If yes, then it shall be merged with master and will be available with next release.
