### ISSUE TITLE
onActivityResult not trigerred

### ISSUE THREAD

**Issue by amirkhoutir** [sandrios/sandriosCamera#16]

**Comment by arpitgandhi9** [comment]
@amirkhoutir Thank you for using the library.. Can you provide some more information.

**Comment by amirkhoutir** [comment]
I'm using the Camera in a Fragment, 
fragment_camera.xml XML Code : 
```
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context="com.team31.plantdetection.fragments.CameraFragment">
    <Button
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:text="take a pic"
        android:id="@+id/take_a_pic"/>

</FrameLayout>
```
CameraFragment.java Code : 
`public class CameraFragment extends Fragment implements View.OnClickListener {


    private static final int CAPTURE_MEDIA = 368;
    private static final String TAG = "spicho";
    private Button button;

    private  void launchCamera() {
        new SandriosCamera(getActivity(),CAPTURE_MEDIA)
                .setShowPicker(false)
                .setMediaAction(CameraConfiguration.MEDIA_ACTION_PHOTO)
                .enableImageCropping(true)
                .launchCamera();
    }


    public CameraFragment() {
        // Required empty public constructor
    }

    /**
     * Use this factory method to create a new instance of
     * this fragment using the provided parameters.
     * @return A new instance of fragment CameraFragment.
     */
    public static CameraFragment newInstance() {
        CameraFragment fragment = new CameraFragment();
        Bundle args = new Bundle();
        fragment.setArguments(args);
        return fragment;
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        Log.d(TAG, "onCreate: ");
        super.onCreate(savedInstanceState);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        // Inflate the layout for this fragment
        Log.d(TAG, "onCreateView: ");
        return inflater.inflate(R.layout.fragment_camera, container, false);
    }
    @Override
    public void onActivityCreated(@Nullable Bundle savedInstanceState) {
        Log.d(TAG, "onActivityCreated: ");
        super.onActivityCreated(savedInstanceState);
        Button button = (Button)getActivity().findViewById(R.id.take_a_pic);

        button.setOnClickListener(this);
    }

    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        
        super.onActivityResult(requestCode, resultCode, data);
        Log.d(TAG, "onActivityResult: ");
        if (requestCode == CAPTURE_MEDIA && resultCode == RESULT_OK) {
            Log.d("spicho","" + data.getStringExtra(CameraConfiguration.Arguments.FILE_PATH));
            Toast.makeText(getActivity(),"Media captured.",Toast.LENGTH_SHORT).show();
        }
    }

    @Override
    public void onClick(View view) {
        launchCamera();
    }
}
`
The problem : When i capture w Photo , OnActivityResult isn't trigured !!

**Comment by amirkhoutir** [comment]
@arpitgandhi9  Thank you for your answer , i've found the problem , I should call OnActivityResult in the activity , not in the Fragment 
Thank you for the amazing library :D 
Have a nice day.

**Comment by arpitgandhi9** [comment]
@amirkhoutir It can be called in fragment as well..
```
    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        if (resultCode == Activity.RESULT_OK) {
        }
    }
```
Just don't call super inside it.
