### ISSUE TITLE
How to hide video record options?

### ISSUE THREAD

**Issue by dzfweb** [sandrios/sandriosCamera#17]
Hi,

i need to know how to hide video record option?
I just wanna to use camera photo. 

*updated*
And how to set the default quality.

Thank you.

**Comment by arpitgandhi9** [comment]
new SandriosCamera(activity, CAPTURE_MEDIA)
                            .setMediaAction(CameraConfiguration.MEDIA_ACTION_PHOTO)
                            .launchCamera();

**Comment by dzfweb** [comment]
@arpitgandhi9  i did it, but the when the camera opens, there is a button to change to video recorder, and i want to hidden it
