### ISSUE TITLE
Directly open fullscreen camera for video record and start automatically 

### ISSUE THREAD

**Issue by hardikJoshi123** [sandrios/sandriosCamera#19]
Hello,

its a great library to record videos. I want to start video recorder directly when user click on buttton, I want to open full screen view which will record video, user can stop video by pressing stop button. Can you suggest if i can do it with this library ? Maximum video recording seconds allow to 20.  Can i directly fire such intent ?

**Comment by arpitgandhi9** [comment]
Please checkout b64a35e and setAutoRecord() while initialising SandriosCamera.
Media Action should be set to Video for this to work.
