### ISSUE TITLE
Enhancements zoom and manual focus trigger ETC

### ISSUE THREAD

**Issue by aftabsikander** [sandrios/sandriosCamera#2]
Hi,
Really a nice library, I have tested it with for devices now and its working fine.  It would be great if you provide zoom and focus trigger feature in next release. As I was testing on Samsung S6 Edge device video was not getting focus while moving around. 

Following are few use case which I believe should be part of this library 

-  Video record duration limit
-  Video file size limit
-  Control over hiding the Video size and Photo size option
-  Include cropping functionality when taking pictures. for this I would prefer using [uCrop.](https://github.com/Yalantis/uCrop)
-  Separate Video and camera option via builder pattern, Because in many cases we would like user to take only video/ image in a particular screen of our application, showing these two options side by side may confuse some of them.

Really an awesome library this these features I am sure many developer would start using your library in production apps.

**Comment by arpitgandhi9** [comment]
Thank You for your support. I have added the Image Cropping and the ability to limit the user to photo or video capture. I'll add the video sizing later.

**Comment by aftabsikander** [comment]
@arpitgandhi9  Thanks, I l check it right away and will let you know how things looks on different devices.

**Comment by aftabsikander** [comment]
@arpitgandhi9  I have given a quick test for the latest library version. Currently I found following cases which might be helpful for you for next release. I will do more extensive testing later today will provide you more test results.

- Crop over all UI is great, But few things which are not properly handled i.e Pinch to zoom, While doing pinch to zoom frequently I was unable to zoom in to the area I wanted to crop. 
- When max zoom level is reached, I feel a sudden jerk or shootout animation on image which unable me to zoom further , This should be disabled or looked deeply why this is happening in the first place.
- Cropping should be a optional flow. Provide a property in your [SandriosCamera ](https://github.com/sandrios/sandriosCamera/blob/master/sandriosCamera/src/main/java/com/sandrios/sandriosCamera/internal/SandriosCamera.java)which enable or disable the cropping feature.
- Cropped Image EXIF data should not be removed. i.e. (Image Meta data containing ISO format focal length ETC). 

I believe Cropping feature should be taken from [uCrop](https://github.com/Yalantis/uCrop) so that you can focus on your core features rather then re inventing the crop wheel.

**Comment by aftabsikander** [comment]
@arpitgandhi9 Have you read this, any update regarding this feedback ?

**Comment by arpitgandhi9** [comment]
@aftabsikander 
I have released a new version that fixes the issues with zoom. It also has the ability to disable crop and fix the size of the video file.

Cheers..🍻

**Comment by arpitgandhi9** [comment]
@aftabsikander According to your recommendation and the issues coming up with the existing image crop code, I have added the uCrop library. 🎉

**Comment by aftabsikander** [comment]
@arpitgandhi9  Great I will take a look into this tomorrow morning, Will perform testing on devices to test flow is not broken.
