### ISSUE TITLE
Video files can't be played in videoview. 

### ISSUE THREAD

**Issue by janshair** [sandrios/sandriosCamera#22]
I recorded a video and store its path. When i tried to play video using this code(Kotlin), i am getting a dialog that states "Can't Play this video" . Here is my code 
```


             SandriosCamera(parentFragment.activity, REQUEST_IMAGE_CAPTURE)
                                  .setShowPicker(false)
                                  .setVideoFileSize(10) //File Size in MB: Default is no limit
                                  .setMediaAction(CameraConfiguration.MEDIA_ACTION_BOTH) // default is CameraConfiguration.MEDIA_ACTION_BOTH
                                  .enableImageCropping(true) // Default is false.
                                  .launchCamera();
```

to get path

`val path : String = data!!.getStringExtra(CameraConfiguration.Arguments.FILE_PATH)
`

and to play
  
```
      videoView.setVideoPath(path)
        videoView.start()
```

![device-2017-06-28-153139](https://user-images.githubusercontent.com/1782608/27642711-8389517c-5c17-11e7-90ff-2a3cd52c5202.png)

**Comment by arpitgandhi9** [comment]
Uri.fromFile(new File(path))
