### ISSUE TITLE
Crash when "Do not keep activities" is enabled

### ISSUE THREAD

**Issue by joerandazzo84** [sandrios/sandriosCamera#23]
Instructions to recreate:

1. Enable 'Do not keep activities' in developer mode
2. Launch camera, then press save on picture
3. After hitting save, the following error occurs.

`Process: com.coolfiresolutions.ronin.sa.base, PID: 17834
java.lang.NullPointerException: Attempt to invoke virtual method 'android.hardware.Camera$Parameters android.hardware.Camera.getParameters()' on a null object reference at com.sandrios.sandriosCamera.internal.manager.impl.Camera1Manager.getPhotoSizeForQuality(Camera1Manager.java:203)`

I found that onPause is called in SandriosCameraActivity which calls onPause on cameraController which nulls out camera before Camera.getParameters is called

**Comment by joerandazzo84** [comment]
@arpitgandhi9 Will this be resolved?

**Comment by arpitgandhi9** [comment]
Values are passed via Intents. Even if catch the exceptions to stop the crash, we wont be able to use the library.
Is there a specific reason for you to use "Do not keep activities".

Also do you have any other suggestions than using activities.
Was thinking of converting it all into fragments, but it is a long process that can take a lot of time.. Will definitely do it but for now can we go ahead with this.

**Comment by mwshubham** [comment]
**How to Enable 'Do not keep activities' in developer mode**? As i am facing the same error. Hope disabling them might give me more information related to issue.
