### ISSUE TITLE
Front Camera

### ISSUE THREAD

**Issue by halilozdemr** [sandrios/sandriosCamera#25]
Can application start with front camera?

**Comment by lmcaluad** [comment]
Hola, dentro del package controller -> impl -> Camera1Controller linea 49, cambia 
currentCameraId = cameraManager.getFaceBackCameraId(); por
currentCameraId = cameraManager.getFaceFrontCameraId(); espero te sirva.

**Comment by halilozdemr** [comment]
Thanks @lmcaluad

**Comment by halilozdemr** [comment]
Thanks @lmcaluad

**Comment by mwshubham** [comment]
changing current camera id works in few device but didn't work on OnePlus 3T. 

_Note: I don't have access to log._

**Comment by mwshubham** [comment]
There is a problem with the flash icon. It becomes visible in Front and gone in Rear camera (on switching camera) 

to resolve this you need to set this
```
int currentCameraType = CameraSwitchView.CAMERA_TYPE_FRONT;
int currentCameraType = CameraSwitchView.CAMERA_TYPE_FRONT;
```

in `BaseSandriosActivity` and `BaseSandriosFragment`

also, comment these line in `CameraControlPanel`
```

        if (hasFlash) {
            flashSwitchView.setVisibility(VISIBLE);
        } else {
            flashSwitchView.setVisibility(GONE);
        }

```
