### ISSUE TITLE
after took photo the result rotate 90 degree

### ISSUE THREAD

**Issue by superdiazzz** [sandrios/sandriosCamera#31]
am using second button in Sample which doesnt implement cropping... i put the result into imageview as setImageBitmap(Bitmap bm)  onActivityResult. But why i got rotating result after then?

**Comment by Mohamed-Fakhry** [comment]
I used this to solve the issue 
https://github.com/jdamcd/android-crop/issues/140#issuecomment-130493867

**Comment by superdiazzz** [comment]
Its working! thanks man
