### ISSUE TITLE
How can I get video thumbnail ?

### ISSUE THREAD

**Issue by jatin-lakhani** [sandrios/sandriosCamera#35]

**Comment by yankelandroid** [comment]
MediaMetadataRetriever mMMR = new MediaMetadataRetriever();

        mMMR.setDataSource(model.getPath());
        //api time unit is microseconds
        Bitmap bitmap = mMMR.getFrameAtTime(1 * 1000000, MediaMetadataRetriever.OPTION_CLOSEST_SYNC);
