### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/karumi/dexter/Dexter;

### ISSUE THREAD

**Issue by zhrfnnn** [sandrios/sandriosCamera#47]
Help ? thanks.

**Comment by iyashamihsan** [comment]
Help!  I also getting the same issue.

**Comment by romrozen** [comment]
Same

**Comment by iyashamihsan** [comment]
@zhrfnnn  and @romrozen  did you find any solution?

**Comment by LazarRistic** [comment]
@iyashamihsan, @zhrfnnn and @romrozen did you find any solution?

**Comment by HeshamMorsy** [comment]
you need to compile these libraries :
1-Glide : [https://github.com/bumptech/glide](url)
2-Dexter : [https://github.com/Karumi/Dexter](url)
3-uCrop : [https://github.com/Yalantis/uCrop](url)

**Comment by arpitgandhi9** [comment]
Sorry for the delay. Please update to version 1.2.6
